name: shoplist
description: My Shopping List.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^2.0.0
  google_fonts: ^1.1.1
  flutter_material_color_picker: ^1.0.5
  flutter_spinbox: ^0.2.1

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true